version: '3.8'

services:
  web:
    container_name: app-backend
    build: .
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
    networks:
      - web_network
    stdin_open: true
    tty: true

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    networks:
      - web_network
    

networks:
  web_network:
    driver: bridge

volumes:
  static_volume:
